# Generated by Django 4.1.2 on 2023-01-03 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63, verbose_name='Навык')),
            ],
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=25)),
                ('info', models.CharField(default='all', max_length=25)),
                ('salary', models.IntegerField()),
                ('count', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('salary', models.IntegerField(verbose_name='Оклад')),
                ('city', models.CharField(max_length=25, verbose_name='Город')),
                ('published', models.DateTimeField(verbose_name='Дата публикации')),
                ('skills', models.ManyToManyField(to='Android_developer.skill')),
            ],
        ),
        migrations.AddField(
            model_name='skill',
            name='vacancies',
            field=models.ManyToManyField(to='Android_developer.vacancy'),
        ),
    ]
