# Generated by Django 4.1.2 on 2023-01-05 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Android_developer', '0002_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='page',
        ),
        migrations.RemoveField(
            model_name='text',
            name='page',
        ),
        migrations.AlterField(
            model_name='content',
            name='content_type',
            field=models.CharField(choices=[('text', 'Текст'), ('image', 'Изображение'), ('table', 'Таблица')], max_length=25),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='Table',
        ),
        migrations.DeleteModel(
            name='Text',
        ),
    ]
