# Generated by Django 4.1.2 on 2023-01-09 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Android_developer', '0004_alter_content_options_alter_style_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'ordering': ['section'], 'verbose_name': 'Содержание блока', 'verbose_name_plural': 'Содержание'},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['page', 'order'], 'verbose_name': 'Блок информации', 'verbose_name_plural': 'Блоки'},
        ),
        migrations.RemoveField(
            model_name='section',
            name='title_styles',
        ),
        migrations.AddField(
            model_name='content',
            name='title_styles',
            field=models.TextField(blank=True),
        ),
    ]
