# Generated by Django 4.1.2 on 2023-01-10 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Android_developer', '0005_alter_content_options_alter_section_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='title_styles',
        ),
        migrations.AddField(
            model_name='content',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Порядок отображения в блоке'),
        ),
        migrations.AlterField(
            model_name='section',
            name='styles',
            field=models.TextField(blank=True, verbose_name='CSS стили для блока'),
        ),
    ]
