# Generated by Django 4.1.2 on 2023-01-14 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Android_developer', '0006_remove_content_title_styles_content_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='style',
            name='content',
        ),
        migrations.RemoveField(
            model_name='content',
            name='order',
        ),
        migrations.RemoveField(
            model_name='section',
            name='display',
        ),
        migrations.AddField(
            model_name='content',
            name='style',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='page',
            field=models.CharField(choices=[('home', 'Главная'), ('relevance', 'Восстребованность'), ('areas', 'География'), ('skills', 'Навыки'), ('vacancies', 'Вакансии')], max_length=25),
        ),
        migrations.DeleteModel(
            name='Page',
        ),
        migrations.DeleteModel(
            name='Style',
        ),
    ]
