# Generated by Django 4.1.2 on 2023-01-14 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Android_developer', '0008_alter_section_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='title_styles',
            field=models.TextField(blank=True, verbose_name='CSS стили для заголовка'),
        ),
        migrations.AddField(
            model_name='section',
            name='title_styles',
            field=models.TextField(blank=True, null=True),
        ),
    ]
